xbcp /y /f Core.u xe:\Warfare\System\
xbcp /y /f Engine.u xe:\Warfare\System\
xbcp /y /f Fire.u xe:\Warfare\System\
xbcp /y /f SoldierSkins.int xe:\Warfare\System\
xbcp /y /f UW.int xe:\Warfare\System\
xbcp /y /f UWindow.u xe:\Warfare\System\
xbcp /y /f UWeb.int xe:\Warfare\System\
xbcp /y /f UWeb.u xe:\Warfare\System\
xbcp /y /f Decorations.u xe:\Warfare\System\
xbcp /y /f Gameplay.u xe:\Warfare\System\
xbcp /y /f Pickups.u xe:\Warfare\System\
xbcp /y /f WarEffects.u xe:\Warfare\System\
xbcp /y /f Warriors.u xe:\Warfare\System\
xbcp /y /f Weapons.u xe:\Warfare\System\
xbcp /y /f AmbientCreatures.u xe:\Warfare\System\
xbcp /y /f Vehicles.u xe:\Warfare\System\
xbcp /y /f WarfareGame.u xe:\Warfare\System\
xbcp /y /f Core.int xe:\Warfare\System\
xbcp /y /f Engine.int xe:\Warfare\System\
xbcp /y /f Window.int xe:\Warfare\System\
xbcp /y /f Setup.int xe:\Warfare\System\
xbcp /y /f xbox.bin xe:\Warfare\